export const cartAT = {
	CART_ID_REQUEST: 'CART_ID_REQUEST',
	CART_ID_SUCCESS: 'CART_ID_SUCCESS',
	CART_ID_FAILURE: 'CART_ID_FAILURE',
	CART_ITEMS_REQUEST: 'CART_ITEMS_REQUEST',
	CART_ITEMS_SUCCESS: 'CART_ITEMS_SUCCESS',
	CART_ITEMS_FAILURE: 'CART_ITEMS_FAILURE',
};
