export const fetchProductsAT = {
	FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
	FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
	FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
	FETCH_ADDITIONAL_PRODUCTS: 'FETCH_ADDITIONAL_PRODUCTS_SUCCESS',
};

export const fetchAdditionalProductsAT = {
	FETCH_ADDITIONAL_PRODUCTS_REQUEST: 'FETCH_ADDITIONAL_PRODUCTS_REQUEST',
	FETCH_ADDITIONAL_PRODUCTS_FAILURE: 'FETCH_ADDITIONAL_PRODUCTS_FAILURE',
	FETCH_ADDITIONAL_PRODUCTS_SUCCESS: 'FETCH_ADDITIONAL_PRODUCTS_SUCCESS',
};

export const addProductToCartAT = {
	ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
	ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
	ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
};

export const deleteProductFromCartAT = {
	DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
	DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
	DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
};
