export const fetchProductsAT = {
	FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
	FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
	FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
	FETCH_ADDITIONAL_PRODUCTS: 'FETCH_ADDITIONAL_PRODUCTS_SUCCESS',
};

export const fetchAdditionalProductsAT = {
	FETCH_ADDITIONAL_PRODUCTS_REQUEST: 'FETCH_ADDITIONAL_PRODUCTS_REQUEST',
	FETCH_ADDITIONAL_PRODUCTS_FAILURE: 'FETCH_ADDITIONAL_PRODUCTS_FAILURE',
	FETCH_ADDITIONAL_PRODUCTS_SUCCESS: 'FETCH_ADDITIONAL_PRODUCTS_SUCCESS',
};
